export const UPDATE_FAKULTETI_BEGIN = "UPDATE_FAKULTETI_BEGIN";
export const UPDATE_FAKULTETI_SUCCESS = "UPDATE_FAKULTETI_SUCCESS";
export const UPDATE_FAKULTETI_ERROR = "UPDATE_FAKULTETI_ERROR";

export const LIST_FAKULTETE_BEGIN = "LIST_FAKULTETI_BEGIN";
export const LIST_FAKULTETE_SUCCESS = "LIST_FAKULTETI_SUCCESS";
export const LIST_FAKULTETE_ERROR = "LIST_FAKULTETI_ERROR";

export const SHTO_FAKULTETE_BEGIN = "SHTO_FAKULTETE_BEGIN";
export const SHTO_FAKULTETE_SUCCESS = "SHTO_FAKULTETE_SUCCESS";
export const SHTO_FAKULTETE_ERROR = "SHTO_FAKULTETE_ERROR";

export const FSHIJ_FAKULTETE_BEGIN = "FSHIJ_FAKULTETE_BEGIN";
export const FSHIJ_FAKULTETE_SUCCESS = "FSHIJ_FAKULTETE_SUCCESS";
export const FSHIJ_FAKULTETE_ERROR = "FSHIJ_FAKULTETE_ERROR";
