export const UPDATE_FAKULTETI_BEGIN = "UPDATE_FAKULTETI_BEGIN";
export const UPDATE_FAKULTETI_SUCCESS = "UPDATE_FAKULTETI_SUCCESS";
export const UPDATE_FAKULTETI_ERROR = "UPDATE_FAKULTETI_ERROR";

export const LIST_FAKULTETE_BEGIN = "LIST_FAKULTETI_BEGIN";
export const LIST_FAKULTETE_SUCCESS = "LIST_FAKULTETI_SUCCESS";
export const LIST_FAKULTETE_ERROR = "LIST_FAKULTETI_ERROR";

export const GET_CURRENT_FAKULTETE_BEGIN = "GET_CURRENT_FAKULTETI_BEGIN";
export const GET_CURRENT_FAKULTETI_SUCCESS = "GET_CURRENT_FAKULTETI_SUCCESS";
export const GET_CURRENT_FAKULTETI_ERROR = "GET_CURRENT_FAKULTETI_ERROR";
