# Generated by Django 4.1.7 on 2023-03-03 09:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smak', '0005_alter_profile_roli_alter_profile_titulli'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periudha', models.CharField(max_length=500)),
                ('cikli', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Per miratim', 'Per miratim'), ('Miratuar', 'Miratuar')], default='Draft', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('programi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iperketprogramit', to='smak.programi')),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='Semestri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestri', models.CharField(choices=[('Semestri 1', 'Semestri 1'), ('Semestri 2', 'Semestri 2')], max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vitiakademik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vitiakademik', models.CharField(max_length=500, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='profile',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='PlanPermbajtja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renditja', models.IntegerField()),
                ('titullari', models.CharField(max_length=500)),
                ('emertimi', models.CharField(max_length=500)),
                ('tipiveprimtarise', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('m', 'm')], max_length=20)),
                ('kredite', models.DecimalField(decimal_places=1, max_digits=2)),
                ('nrjavesem1', models.IntegerField()),
                ('seminaresem1', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('leksionesem1', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('praktikasem1', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('laboratoresem1', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('nrjavesem2', models.IntegerField()),
                ('seminaresem2', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('leksionesem2', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('praktikasem2', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('laboratoresem2', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('plani', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iperketplanit', to='smak.planet')),
                ('semestri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iperketsemestrit', to='smak.semestri')),
            ],
            options={
                'ordering': ['-renditja'],
            },
        ),
        migrations.AddIndex(
            model_name='planpermbajtja',
            index=models.Index(fields=['-plani', '-semestri'], name='smak_planpe_plani_i_245f78_idx'),
        ),
        migrations.AddIndex(
            model_name='planet',
            index=models.Index(fields=['-periudha', '-programi'], name='smak_planet_periudh_0fad09_idx'),
        ),
    ]
