# Generated by Django 4.1.7 on 2023-03-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smak', '0006_planet_semestri_vitiakademik_profile_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
