# Generated by Django 4.1.7 on 2023-03-03 10:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smak', '0008_alter_profile_roli'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='roli',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), size=None),
        ),
    ]
