# Generated by Django 4.1.7 on 2023-03-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smak', '0009_alter_profile_roli'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planpermbajtja',
            old_name='laboratoresem1',
            new_name='laboratore',
        ),
        migrations.RenameField(
            model_name='planpermbajtja',
            old_name='leksionesem2',
            new_name='leksione',
        ),
        migrations.RenameField(
            model_name='planpermbajtja',
            old_name='nrjavesem1',
            new_name='nrjave',
        ),
        migrations.RenameField(
            model_name='planpermbajtja',
            old_name='praktikasem1',
            new_name='praktika',
        ),
        migrations.RenameField(
            model_name='planpermbajtja',
            old_name='seminaresem1',
            new_name='seminare',
        ),
        migrations.RemoveField(
            model_name='planpermbajtja',
            name='laboratoresem2',
        ),
        migrations.RemoveField(
            model_name='planpermbajtja',
            name='leksionesem1',
        ),
        migrations.RemoveField(
            model_name='planpermbajtja',
            name='nrjavesem2',
        ),
        migrations.RemoveField(
            model_name='planpermbajtja',
            name='praktikasem2',
        ),
        migrations.RemoveField(
            model_name='planpermbajtja',
            name='seminaresem2',
        ),
        migrations.AlterField(
            model_name='planpermbajtja',
            name='kredite',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
