# Generated by Django 4.1.7 on 2023-03-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smak', '0010_rename_laboratoresem1_planpermbajtja_laboratore_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planpermbajtja',
            name='viti',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
