# Generated by Django 4.1.7 on 2023-03-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smak', '0011_planpermbajtja_viti'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='planpermbajtja',
            name='smak_planpe_plani_i_245f78_idx',
        ),
        migrations.RenameField(
            model_name='planpermbajtja',
            old_name='laboratore',
            new_name='laboratoresem1',
        ),
        migrations.RenameField(
            model_name='planpermbajtja',
            old_name='leksione',
            new_name='leksionesem1',
        ),
        migrations.RenameField(
            model_name='planpermbajtja',
            old_name='nrjave',
            new_name='nrjavesem1',
        ),
        migrations.RenameField(
            model_name='planpermbajtja',
            old_name='praktika',
            new_name='praktikasem1',
        ),
        migrations.RenameField(
            model_name='planpermbajtja',
            old_name='seminare',
            new_name='seminaresem1',
        ),
        migrations.RemoveField(
            model_name='planpermbajtja',
            name='semestri',
        ),
        migrations.AddField(
            model_name='planpermbajtja',
            name='laboratoresem2',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='planpermbajtja',
            name='leksionesem2',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='planpermbajtja',
            name='nrjavesem2',
            field=models.IntegerField(default=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planpermbajtja',
            name='praktikasem2',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='planpermbajtja',
            name='semestri1',
            field=models.CharField(blank=True, choices=[('P', 'P'), ('F', 'F')], max_length=2),
        ),
        migrations.AddField(
            model_name='planpermbajtja',
            name='semestri2',
            field=models.CharField(blank=True, choices=[('P', 'P'), ('F', 'F')], max_length=2),
        ),
        migrations.AddField(
            model_name='planpermbajtja',
            name='seminaresem2',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AddIndex(
            model_name='planpermbajtja',
            index=models.Index(fields=['-plani'], name='smak_planpe_plani_i_6ee31c_idx'),
        ),
    ]
