# Generated by Django 4.1.7 on 2023-03-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smak', '0012_remove_planpermbajtja_smak_planpe_plani_i_245f78_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planpermbajtja',
            name='nrjavesem2',
            field=models.IntegerField(default=0),
        ),
    ]
