# Generated by Django 4.1.7 on 2023-03-08 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smak', '0013_alter_planpermbajtja_nrjavesem2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planpermbajtja',
            options={'ordering': ['renditja']},
        ),
        migrations.AlterField(
            model_name='planpermbajtja',
            name='kredite',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
