# Generated by Django 4.1.7 on 2023-03-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smak', '0014_alter_planpermbajtja_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planpermbajtja',
            name='titullari',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
