# Generated by Django 4.1.7 on 2023-03-17 14:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smak', '0015_alter_planpermbajtja_titullari'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='roli',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Pedagog', 'Pedagog'), ('ShefDep', 'ShefDep'), ('Dekan', 'Dekan'), ('Rektor', 'Rektor'), ('Kurrikula', 'Kurrikula'), ('Admin', 'Admin')], max_length=32), size=None),
        ),
    ]
