# Generated by Django 4.1.7 on 2023-03-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smak', '0017_lendemezgjedhje'),
    ]

    operations = [
        migrations.AddField(
            model_name='lendemezgjedhje',
            name='viti',
            field=models.IntegerField(default=1),
        ),
    ]
