# Generated by Django 4.1.7 on 2023-03-19 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smak', '0019_remove_lendemezgjedhje_plani'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lendemezgjedhje',
            name='viti',
        ),
    ]
