# Generated by Django 4.1.7 on 2023-04-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smak', '0020_remove_lendemezgjedhje_viti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planpermbajtja',
            name='laboratoresem1',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='planpermbajtja',
            name='laboratoresem2',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='planpermbajtja',
            name='leksionesem1',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='planpermbajtja',
            name='leksionesem2',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='planpermbajtja',
            name='nrjavesem1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='planpermbajtja',
            name='praktikasem1',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='planpermbajtja',
            name='praktikasem2',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='planpermbajtja',
            name='seminaresem1',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='planpermbajtja',
            name='seminaresem2',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
